const ar = {
  Profile: "الملف الشخصي",
  About: "حول",
  Account: "الحساب",
  Logout: "تسجيل الخروج",
  "Change Language": "تغيير اللغة",
  English: "الإنجليزية",
  Arabic: "العربية",
  Password: "كلمة المرور",
  "Privacy policy": "سياسة الخصوصية",
  "About Us": "معلومات عنا",
  "Payout methods": "طرق الدفع",
  "Payment methods": "طرق الدفع",
  Edit: "تعديل",
  "Phone Number": "رقم الهاتف",
  Mail: "البريد الإلكتروني",
  Age: "العمر",
  Gender: "الجنس",
  Name: "الاسم",
  "ID verified": "تم التحقق من الهوية",
  "Confirm your email": "أكد بريدك الإلكتروني",
  "Confirmed phone number": "تم تأكيد رقم الهاتف",
  "Travel Preferences": "تفضيلات السفر",
  "I'm chatty when I feel comfortable": "أتحدث عندما أشعر بالراحة",
  "Cigarette breaks outside the car are ok":
    "استراحات التدخين خارج السيارة مقبولة",
  "I'll jam depending on the mood": "سأستمع للموسيقى حسب المزاج",
  "I'll travel with pets depending on the animal":
    "سأسافر مع الحيوانات الأليفة حسب نوع الحيوان",
  "About you": "عن نفسك",
  "Dedicated to making travel more convenient and cost-effective, he prioritizes safety, punctuality, and passenger comfort. By providing a reliable and efficient service, he ensures that commuters enjoy a smooth and stress-free journey. His commitment to shared transportation allows passengers to save money while reducing environmental impact. Beyond just a ride, he fosters a sense of community among travelers, encouraging connections and a more enjoyable commuting experience. His dependable service transforms everyday travel into a seamless, shared experience.":
    "مكرس لجعل السفر أكثر سهولة وفعالية من حيث التكلفة، يعطي الأولوية للسلامة والدقة وراحة الركاب. من خلال تقديم خدمة موثوقة وفعالة، يضمن أن يستمتع الركاب برحلة سلسة وخالية من التوتر. التزامه بالنقل المشترك يسمح للركاب بتوفير المال وتقليل الأثر البيئي. بالإضافة إلى مجرد رحلة، يعزز روح المجتمع بين المسافرين، ويشجع على التواصل وتجربة تنقل أكثر متعة. خدمته الموثوقة تحول السفر اليومي إلى تجربة مشتركة سلسة.",
  Vehicles: "المركبات",
  "Sedan, Black": "سيدان، أسود",
  "Add vehicle": "إضافة مركبة",
  Male: "ذكر",
  profile: {
    verificationEmailSent:
      "لقد أرسلنا رابط التحقق إلى عنوان بريدك الإلكتروني. يرجى التحقق من صندوق الوارد الخاص بك.",
    ok: "حسنًا",
    vehicle: "المركبة",
    enterVehicleName: "أدخل اسم المركبة",
    selectCategory: "اختر الفئة",
    sedan: "سيدان",
    luxury: "فاخرة",
    suv: "دفع رباعي",
    continue: "متابعة",
    vehicleModel: "طراز المركبة",
    vehicleColor: "لون المركبة",
    add: "إضافة",
    changePassword: "تغيير كلمة المرور",
    passwordRequirements:
      "يجب أن تحتوي على 8 أحرف على الأقل، وحرف واحد، ورقم واحد، وحرف خاص واحد.",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmNewPassword: "تأكيد كلمة المرور الجديدة",
    save: "حفظ",
    selectPaymentMethod: "اختر طريقة الدفع",
    creditDebitCards: "بطاقات الائتمان والخصم",
    addNewCard: "+ إضافة بطاقة جديدة",
    otherUpiApps: "تطبيقات UPI الأخرى",
    addNew: "+ إضافة جديد",
    loading: "جاري التحميل...",
    noItems: "لا توجد عناصر.",
    colors: {
      black: "أسود",
      red: "أحمر",
      yellow: "أصفر",
      green: "أخضر",
    },
  },
  index: {
    verify_phone_number: "تحقق من رقم هاتفك",
    no_special_offers:
      "لا أرغب في تلقي عروض خاصة وتوصيات مخصصة عبر الرسائل النصية أو المكالمات",
    agreement_text:
      "بإدخال رقم هاتفك، فإنك توافق على تلقي رسائل ترويجية عبر الرسائل النصية وواتساب والمكالمات من BlaBlaCar. يمكنك إلغاء الاشتراك الآن عن طريق تحديد المربع أعلاه أو في أي وقت من إعدادات ملفك الشخصي.",
    do_it_later: "سأفعل ذلك لاحقًا",
  },
  components: {
    // phone-input
    "Phone Number": "رقم الهاتف",
    mobile_number: "رقم الجوال",
    book: {
      title: "اختيارك من الرحلات في",
      affordable: "سعر مناسب",
      prices: "أسعار",
    },
    pickup: {
      title: "من أين ستنطلق؟",
    },
    common: {
      continue: "استمر",
      save: "حفظ",
    },
    yourRides: {
      title: "رحلاتك",
      tabs: {
        Pending: "قيد الانتظار",
        Cancelled: "ملغي",
        Completed: "مكتمل",
        "In Progress": "جاري"
      },
    },
    inbox: {
      title: "صندوق الوارد",
      nameEn: "Mohammed Arshad",
      nameAr: "محمد أرشد",
      fromValue: "الخبر",
      toValue: "الرياض",
      dateValue: "الخميس، 06 فبراير",
      timeValue: "08 : 00 م",
      from: "{{from}}",
      to: "{{to}}",
      date: "{{date}}",
      time: "{{time}}",
    },
    // verify-otp
    Verify: "تحقق",
    "Please Verify Your Number": "يرجى التحقق من رقمك",
    "Please enter the six-digit verification code that we have sent to your mobile number ending in":
      "يرجى إدخال رمز التحقق المكون من ستة أرقام الذي أرسلناه إلى رقم هاتفك المنتهي بـ",
    "If you haven't received the code, please check your messages or":
      "إذا لم تستلم الرمز، يرجى التحقق من رسائلك أو",
    "request a new code.": "طلب رمز جديد.",
    endingDigits: " {{digits}}.",
    // passenger-select
    Passenger: "راكب",
    "Select no. of passengers": "اختر عدد الركاب",
    "Passenger(s)": "راكب/ركاب",
    // auto-complete
    "Search...": "بحث...",
    // city-search
    "Enter the full address": "أدخل العنوان الكامل",
    "No items.": "لا توجد عناصر.",
    "Mobile number*": "رقم الجوال*",
    // ride-status-item
    Completed: "مكتمل",
    Pending: "قيد الانتظار",
    Cancelled: "ملغي",
    Invoice: "فاتورة",
    searchRide: {
      title: "إلى أين تريد الذهاب؟",
      pickupPlaceholder: "أدخل موقع الانطلاق",
      dropPlaceholder: "أدخل موقع الوصول",
      searchButton: "بحث",
      "missingLocation": "يرجى اختيار موقعي الانطلاق والوصول.",
      "missingDate": "يرجى اختيار تاريخ الرحلة."
    },
    locationSelect: {
      placeholder: "ابحث عن الموقع...",
      emptyMessage: "لا توجد نتائج.",
    },
    datePicker: {
      scheduleTrip: "جدولة الرحلة",
      pickDate: "اختر تاريخًا",
      today: "اليوم",
      tomorrow: "غدًا",
      apply: "تطبيق",
    },
    rideFilter: {
      filter: "فلتر",
      resetAll: "إعادة تعيين الكل",
      sortBy: "ترتيب حسب",
      clearAll: "مسح الكل",
      earliestDeparture: "أقرب موعد انطلاق",
      lowestPrice: "أقل سعر",
      closeToDeparture: "قريب من نقطة الانطلاق",
      closeToArrival: "قريب من نقطة الوصول",
      shortestRide: "أقصر رحلة",
      numberOfStops: "عدد التوقفات",
      directRidesOnly: "رحلات مباشرة فقط",
      oneStop: "توقف واحد",
      twoStopsOrMore: "توقفين أو أكثر",
      trustAndSafety: "الثقة والأمان",
      verifiedProfile: "الملف الشخصي المؤكد",
      amenities: "المرافق",
      carModel: "موديل السيارة",
      lastThreeYears: "آخر 3 سنوات",
      lastFiveYears: "آخر 5 سنوات",
      all: "الكل",
      apply: "تطبيق",
    },
    checkboxCard: {
      maxTwoInBack: "حد أقصى 2 في الخلف",
      instantBooking: "الحجز الفوري",
      smokingAllowed: "التدخين مسموح",
      petsAllowed: "الحيوانات الأليفة مسموحة",
      powerOutlets: "منافذ الطاقة",
      airConditioning: "التكييف",
      accessibleForDisabilities: "متاح للركاب ذوي الإعاقة",
    },
    rideDetails: {
      rideDetails: "تفاصيل الرحلة",
      pickup: "الانطلاق",
      drop: "الوصول",
      pickupTime: "وقت الانطلاق",
      dropTime: "وقت الوصول",
      alKhobar: "الخبر، المملكة العربية السعودية",
      riyadh: "الرياض، المملكة العربية السعودية",
      departureTime: "13:00",
      arrivalTime: "17:40",
      carType: "نوع السيارة",
      sedan: "سيدان",
      details: "التفاصيل",
      rarelyCancelsRides: "نادراً ما يلغي الرحلات",
      instantBooking: "سيتم تأكيد حجزك فوراً",
      fineWithSmoking: "أنا بخير مع التدخين",
      passengers: "الركاب",
      priceSummary: "ملخص السعر",
      onePassenger: "راكب واحد",
      amountPaidToDriver: "المبلغ المدفوع للسائق",
      serviceFeeAndVAT: "رسوم الخدمة والضريبة",
      totalPrice: "السعر الإجمالي",
      manageRide: "إدارة الرحلة",
      ratings: "التقييمات",
      abhimanyu: "أبهيما نيو",
      karthik: "كارثيك",
      chennai: "تشيناي",
      banglaluru: "بنغالورو",
      rating: "4.5",
      currency: "ر.س",
    },
    payment: {
      selectPaymentMethod: "اختر طريقة الدفع",
      creditDebitCards: "بطاقات الائتمان والخصم",
      addNewCard: "+ إضافة بطاقة جديدة",
      otherUpiApps: "تطبيقات UPI الأخرى",
      addNew: "+ إضافة جديد",
      amount: "المبلغ",
      pay: "ادفع",
      waitingApproval: "في انتظار موافقة السائق",
      bookingConfirmed: "تم تأكيد حجزك بنجاح!",
      visa: "فيزا تنتهي بـ 5775",
      mastercard: "ماستر تنتهي بـ 5775",
      expiry: "تاريخ الانتهاء 06/27",
      applePay: "Apple Pay",
      samsungPay: "Samsung Pay",
      currency: "ر.س",
    },
    chat: {
      abhimanyu: "أبهيمانيو",
      alKhobar: "الخبر، المملكة العربية السعودية",
      awaitingApproval: "بانتظار الموافقة",
      new: "جديد",
      guidelinesNotice:
        "قد نقوم بمراجعة الرسائل. يمكنك أيضًا الإبلاغ عن الرسائل غير اللائقة من",
      guidelinesPage: "صفحة الإرشادات الخاصة بنا.",
      scamWarning:
        "لتجنب الاحتيال، لا تقم أبدًا بزيارة الروابط المرسلة من الأعضاء للدفع أو تحويل الأموال.",
      learnMore: "اعرف المزيد.",
      yourMessage: "رسالتك",
      messagingGuidelines: "إرشادات المراسلة",
      guidelines1:
        "يرجى عدم تضمين رقم هاتفك أو بريدك الإلكتروني أو أي عناوين مواقع إلكترونية.",
      guidelines2:
        "قد نقوم بتصفية كل أو جزء من رسالتك، خاصة إذا كانت تتضمن معلومات اتصال، حيث أن ذلك مخالف لـ",
      terms: "الشروط والأحكام.",
      close: "إغلاق",
      hello: "مرحبًا",
      dateTime: "الخميس، 06 فبراير 08 : 00 مساءً",
    },
    chatProfile: {
      profile: "الملف الشخصي",
      reportNumber: "الإبلاغ عن هذا الرقم",
      abhimanyu: "أبهيمانيو",
      alBalad: "البلد، المملكة العربية السعودية",
      confirmedMail: "تم تأكيد البريد الإلكتروني",
      confirmedPhone: "تم تأكيد رقم الهاتف",
      ridePublished: "رحلة منشورة",
      about: "حول",
      phoneNumber: "رقم الهاتف",
      mailId: "البريد الإلكتروني",
      experience: "الخبرة",
      intermediate: "متوسط",
      aboutText:
        "جعل السفر أكثر سهولة وفعالية من حيث التكلفة للركاب. مع التزام قوي بالسلامة والدقة، يضمن رحلة سلسة ومريحة. تساعد خدمته الموثوقة الركاب على مشاركة الرحلات بكفاءة مع تعزيز روح المجتمع على الطريق.",
    },
    passengerProfile: {
      profile: "الملف الشخصي",
      reportNumber: "الإبلاغ عن هذا الرقم",
      abhimanyu: "أبهيمانيو",
      alBalad: "البلد، المملكة العربية السعودية",
      confirmedMail: "تم تأكيد البريد الإلكتروني",
      confirmedPhone: "تم تأكيد رقم الهاتف",
      about: "حول",
      aboutText:
        "جعل السفر أكثر سهولة وفعالية من حيث التكلفة للركاب. مع التزام قوي بالسلامة والدقة، يضمن رحلة سلسة ومريحة. تساعد خدمته الموثوقة الركاب على مشاركة الرحلات بكفاءة مع تعزيز روح المجتمع على الطريق.",
    },
    tabs: {
      home: "الرئيسية",
      publish: "نشر",
      yourRides: "رحلاتك",
      inbox: "الوارد",
      profile: "الملف الشخصي",
    },
    pickupSelected: {
      title: "أين ترغب في اصطحاب الركاب؟",
    },
    locationSearchSelected: {
      label: "اختر الموقع",
      continue: "استمر",
      whyExactLocation: "لماذا الموقع الدقيق؟",
    },
    dropoff: {
      title: "إلى أين ستذهب؟",
      selectedTitle: "أين ترغب في إنزال الركاب؟",
    },
    route: {
      title: "ما هو مسارك؟",
      option1: {
        title: "٤ ساعات ١٥ دقيقة",
        description: "٣٤٦ كم - طريق هوسور وNH 4/NH 44/NH 48",
      },
      option2: {
        title: "٤ ساعات ٤٠ دقيقة",
        description: "٣٤٦ كم - طريق هوسور وNH 4/NH 44/NH 48",
      },
      option3: {
        title: "٥ ساعات ١٠ دقيقة",
        description: "٣٤٦ كم - طريق هوسور وNH 4/NH 44/NH 48",
      },
    },
    stopovers: {
      title: "أضف محطات توقف للحصول على المزيد من الركاب",
      addCity: "أضف مدينة",
      city1: "الدمام",
      city2: "منتجع سدرة",
      city3: "جودة",
    },
    stopoversPreview: {
      title: "هذه هي أفضل أماكن التوقف. هل تناسبك؟",
      start: "الدمام",
      end: "الرياض",
      stop1: {
        title: "قرية التراث",
        desc: "طريق الكورنيش، الدمام، السعودية",
      },
    },
    date: {
      title: "متى ستذهب؟",
    },
    time: {
      title: "في أي وقت ستقل الراكب؟",
      am: "ص",
      pm: "م",
    },
    passengerCount: {
      title: "كم عدد ركاب فياكار الذين يمكنك اصطحابهم؟",
      options: "خيارات الركاب",
      maxTwoInBack: "حد أقصى 2 في الخلف",
      comfortHint: "لراحتك، اترك المقعد الأوسط فارغًا",
    },
    pricing: {
      title: "حدد سعرك لكل مقعد",
      recommended: "السعر الموصى به:",
      hint: "سعر مثالي لهذه الرحلة! ستحصل على ركاب بسرعة.",
      showPrices: "عرض الأسعار",
    },
    showPricing: {
      rideDetails: "تفاصيل الرحلة",
      pickup: "الانطلاق",
      drop: "الوصول",
      stopover: "محطة توقف",
      alKhobar: "الخبر، المملكة العربية السعودية",
      riyadh: "الرياض، المملكة العربية السعودية",
      heritageVillage: "قرية التراث، الدمام، السعودية",
    },
    returnRide: {
      title: "هل ستعود أيضًا؟انشر رحلة العودة الآن!",
      publishNow: "انشر رحلة العودة الخاصة بي",
      publishLater: "سأنشر رحلة العودة لاحقًا",
    },
    publishComment: {
      title: "هل لديك أي شيء تضيفه عن رحلتك؟",
      placeholder:
        "هل أنت مرن بشأن مكان ووقت اللقاء؟ لن تسلك الطريق السريع؟ لديك مساحة محدودة في الصندوق؟ أبقِ الراكب على اطلاع.",
      publish: "انشر الرحلة",
    },
    publishRide: {
      success: "تم نشر رحلتك بنجاح وهي الآن نشطة!",
      verifyProfile: "خطوة أخيرة: نحتاج إلى التحقق من ملفك الشخصي",
      verifyId: "تحقق من الهوية",
      confirmedPhone: "تم تأكيد رقم الهاتف",
      seeMyRide: "عرض رحلتي",
      emailSent:
        "لقد أرسلنا رابط تحقق إلى بريدك الإلكتروني. يرجى التحقق من صندوق الوارد.",
      ok: "حسنًا",
    },
    yourRide: {
      title: "خطة الرحلة",
      pickup: "الانطلاق",
      drop: "الوصول",
      pickupTime: "وقت الانطلاق",
      dropTime: "وقت الوصول",
      seePublication: "عرض منشورك عبر الإنترنت",
      views: "3 مشاهدات",
      editPublication: "تعديل منشورك",
      alKhobar: "الخبر، المملكة العربية السعودية",
      riyadh: "الرياض، المملكة العربية السعودية",
      departureTime: "13:00",
      arrivalTime: "17:40",
    },
    yourPublication: {
      title: "منشورك",
      itinerary: "تفاصيل خط الرحلة",
      route: "المسار",
      price: "السعر",
      priceSub: "سيدفع الركاب نقدًا",
      seatOptions: "المقعد والخيارات",
      duplicate: "نسخ منشورك",
      publishReturn: "انشر رحلة العودة الخاصة بك",
      cancel: "إلغاء رحلتك",
    },
    itinerary: {
      title: "تفاصيل خط الرحلة",
      start: "الدمام",
      stopTitle: "قرية التراث",
      stopDesc: "طريق الكورنيش، الدمام، السعودية",
      end: "الرياض",
      date: "التاريخ",
      dateValue: "الخميس، 13 فبراير",
      time: "الوقت",
      timeValue: "07:00 ص",
      manageStopovers: "إدارة محطات التوقف",
    },
    stopoversEdit: {
      title: "أضف محطات توقف للحصول على المزيد من الركاب",
      addCity: "أضف مدينة",
      continue: "استمر",
      cities: ["الدمام", "منتجع سدرة", "جودة"],
    },
    rideStatusItem: {
      departureTime: "13:00",
      departureLocation: "الخبر، المملكة العربية السعودية",
      duration: "4س 40د",
      arrivalTime: "17:40",
      arrivalLocation: "الرياض، المملكة العربية السعودية",
      price: "ر.س 560.00",
      driverName: "أبهيما نيو",
      rating: "4.5",
      Completed: "مكتمل",
      Invoice: "فاتورة",
      Pending: "قيد الانتظار",
      Cancelled: "ملغي",
    },
  },
  booking: {
    ride: {
      location: "تشيناي، تاميل نادو...",
      todayPassenger: "اليوم، راكب واحد",
      filters: "فلاتر",
      today: "اليوم",
      createAlert: "إنشاء تنبيه رحلة",
      enterEmail: "أدخل بريدك الإلكتروني وسنقوم بإعلامك.",
      pickup: "الانطلاق",
      pickupLocation: "الخبر، المملكة العربية السعودية",
      drop: "الوصول",
      dropLocation: "الرياض، المملكة العربية السعودية",
      emailInstruction:
        "يرجى إدخال بريدك الإلكتروني الكامل حتى نتمكن من إرسال تفاصيل الرحلة والإشعارات.",
      emailPlaceholder: "أدخل بريدك الإلكتروني",
      rideAlert: "تنبيه رحلة",
    },
    rideItem: {
      departureTime: "13:00",
      departureLocation: "الخبر، المملكة العربية السعودية",
      duration: "4س 40د",
      arrivalTime: "17:40",
      arrivalLocation: "الرياض، المملكة العربية السعودية",
      price: "ر.س 560.00",
      driverName: "أبهيما نيو",
      rating: "4.5",
    },
  },
  Abhimanyu: "أبهيما نيو",
};

export default ar;
