const en = {
  Profile: "Profile",
  About: "About",
  Account: "Account",
  Logout: "Logout",
  "Change Language": "Change Language",
  English: "English",
  Arabic: "Arabic",
  Password: "Password",
  "Privacy policy": "Privacy policy",
  "About Us": "About Us",
  "Payout methods": "Payout methods",
  "Payment methods": "Payment methods",
  Edit: "Edit",
  "Phone Number": "Phone Number",
  Mail: "Mail",
  Age: "Age",
  Gender: "Gender",
  Name: "Name",
  "ID verified": "ID verified",
  "Confirm your email": "Confirm your email",
  "Confirmed phone number": "Confirmed phone number",
  "Travel Preferences": "Travel Preferences",
  "I'm chatty when I feel comfortable": "I'm chatty when I feel comfortable",
  "Cigarette breaks outside the car are ok":
    "Cigarette breaks outside the car are ok",
  "I'll jam depending on the mood": "I'll jam depending on the mood",
  "I'll travel with pets depending on the animal":
    "I'll travel with pets depending on the animal",
  "About you": "About you",
  "Dedicated to making travel more convenient and cost-effective, he prioritizes safety, punctuality, and passenger comfort. By providing a reliable and efficient service, he ensures that commuters enjoy a smooth and stress-free journey. His commitment to shared transportation allows passengers to save money while reducing environmental impact. Beyond just a ride, he fosters a sense of community among travelers, encouraging connections and a more enjoyable commuting experience. His dependable service transforms everyday travel into a seamless, shared experience.":
    "Dedicated to making travel more convenient and cost-effective, he prioritizes safety, punctuality, and passenger comfort. By providing a reliable and efficient service, he ensures that commuters enjoy a smooth and stress-free journey. His commitment to shared transportation allows passengers to save money while reducing environmental impact. Beyond just a ride, he fosters a sense of community among travelers, encouraging connections and a more enjoyable commuting experience. His dependable service transforms everyday travel into a seamless, shared experience.",
  Vehicles: "Vehicles",
  "Sedan, Black": "Sedan, Black",
  "Add vehicle": "Add vehicle",
  Male: "Male",
  profile: {
    verificationEmailSent:
      "We've sent a verification link to your email address. Please check your inbox.",
    ok: "OK",
    vehicle: "Vehicle",
    enterVehicleName: "Search vehicle name",
    selectCategory: "Select Category",
    sedan: "Sedan",
    luxury: "Luxury",
    suv: "SUV",
    continue: "Continue",
    vehicleModel: "Vehicle Model",
    vehicleColor: "Vehicle Color",
    add: "Add",
    adding: "Adding",
    pleaseSelectColor: "Please select a color",
    vehicleModelRequired: "Vehicle model is required",
    vehicleAddedSuccessfully: "Vehicle added successfully",
    failedToAddVehicle: "Failed to add vehicle",
    changePassword: "Change Password",
    passwordRequirements:
      "It must have at least 8 characters, 1 letter, 1 number and 1 special character.",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmNewPassword: "Confirm new password",
    save: "Save",
    selectPaymentMethod: "Select a payment method",
    creditDebitCards: "Credit & DEBIT CARDS",
    addNewCard: "+ ADD NEW CARD",
    otherUpiApps: "OTHER UPI APPS",
    addNew: "+ ADD NEW",
    loading: "Loading...",
    noItems: "No items.",
    colors: {
      black: "Black",
      red: "Red",
      yellow: "Yellow",
      green: "Green",
    },
    "Bank Account": "Bank Account",
    "Transactions": "Transactions",
    "Terms & Conditions": "Terms & Conditions",
    "Privacy Policy": "Privacy Policy",
    "Delete Vehicle": "Delete Vehicle",
    "Are you sure you want to delete this vehicle?": "Are you sure you want to delete this vehicle?",
    "Cancel": "Cancel",
    "Delete": "Delete",
    "Success": "Success",
    "Vehicle deleted successfully": "Vehicle deleted successfully",
    "Error": "Error",
    "Failed to delete vehicle": "Failed to delete vehicle",
    "No vehicles added yet": "No vehicles added yet",
    "Email confirmed": "Email confirmed",
    "Close my account": "Close my account",
    "Select Vehicle": "Select Vehicle",
    "Language": "Language",
    "Select Language": "Select Language",
    "Current Language": "Current Language",
    "App needs to restart to apply language changes": "App needs to restart to apply language changes",
    "Are you sure you want to logout?": "Are you sure you want to logout?",
    editVehicle: "Edit Vehicle",
    brandModel: "Brand & Model",
    tapToChange: "Tap to change",
    searchBrand: "Search brand",
    category: "Category",
    loadingCategories: "Loading categories...",
    model: "Model",
    searchModel: "Search model",
    color: "Color",
    selectVehicleColor: "Select vehicle color",
    year: "Year",
    enterYear: "Enter year (e.g., 2024)",
    updateVehicle: "Update Vehicle",
    updating: "Updating...",
    colorRequired: "Color is required",
    yearRequired: "Year is required",
    yearMustBe4Digits: "Year must be 4 digits",
    yearRange: "Year must be between {{min}} and {{max}}",
    pleaseFixErrors: "Please fix the errors before continuing",
    vehicleDataMissing: "Vehicle data is missing",
    modelIdRequired: "Model ID is required",
    vehicleUpdatedSuccessfully: "Vehicle updated successfully",
  },
  "Something went wrong": "Something went wrong",
  "Add about you here": "Add about you here",
  "Add Travel Preferences": "Add Travel Preferences",
  "Add About": "Add About",
  "Add your travel preferences here": "Add your travel preferences here",
  "Preferences": "Preferences",
  "Enter travel preferences": "Enter travel preferences",
  "Loading...": "Loading...",
  "No preferences added yet": "No preferences added yet",
  "error": "Error",
  "success": "Success",
  verify_your_profile: "Verify your profile",
  firstName: "First Name",
  lastName: "Last Name",
  firstNamePlaceholder: "Enter first name",
  lastNamePlaceholder: "Enter last name",
  selectGender: "Select Gender",
  chooseGender: "Choose your gender",
  male: "Male",
  female: "Female",
  other: "Other",
  registrationError: "Registration Error",
  firstNameRequired: "First name is required",
  firstNameMinLength: "First name must be at least 2 characters",
  firstNameLettersOnly: "First name can only contain letters",
  lastNameRequired: "Last name is required",
  lastNameMinLength: "Last name must be at least 2 characters",
  lastNameLettersOnly: "Last name can only contain letters",
  dobRequired: "Date of birth is required",
  ageMinimum: "You must be at least 18 years old",
  genderRequired: "Gender selection is required",
  fillAllFields: "Please fill in all required fields correctly",
  sessionExpired: "Session expired. Please try logging in again",
  registrationFailed: "Registration failed. Please try again",
  connectionError: "Registration failed. Please check your connection and try again",
  login: {
    verify_phone_number: "Verify your phone number",
    no_special_offers:
      "You agree to Privacy Policy and Terms of Use",
    agreement_text:
      "By entering your phone number, you agree to receive promotional SMS, WhatsApp messages and calls from Via Car.",
    do_it_later: "I'll do it later",
    continue_as_guest: "Continue as Guest",
    phone_min_digits: "Phone number must be at least 8 digits",
    phone_max_digits: "Phone number cannot exceed 15 digits",
    sending: "Sending...",
    verifying: "Verifying...",
    invalid_phone: "Invalid Phone Number",
    invalid_phone_message: "Please enter a valid phone number with at least 8 digits.",
    otp_sent: "OTP Sent",
    otp_sent_message: "Verification code has been sent to your phone.",
    otp_failed: "OTP Failed",
    invalid_otp: "Invalid OTP",
    invalid_otp_message: "Please enter the complete 6-digit verification code.",
    session_error: "Session Error",
    session_error_message: "OTP session expired. Please request a new code.",
    verification_failed: "Verification Failed",
  },
  components: {
    // phone-input
    "Phone Number": "Phone Number",
    mobile_number: "Mobile number",
    book: {
      title: "Your Selection of Rides at",
      affordable: "Affordable",
      prices: "Prices",
    },
    pickup: {
      title: "Where are you leaving from?",
      setupDialog: {
        title: "Complete Your Profile Setup",
        subtitle: "Complete these steps to start publishing rides",
        steps: {
          login: "Login to your account",
          bank: "Add bank details",
          verification: "Complete identity verification",
          vehicle: "Add vehicle information"
        },
        status: {
          completed: "Completed",
          pending: "Verification pending"
        },
        buttons: {
          setup: "Setup →",
          later: "I'll do this later"
        }
      },
      messages: {
        selectLocation: "Select your pickup location to continue",
        locationRequired: "Please select a pickup location to continue",
        setupRequired: "Complete your profile setup to publish rides"
      }
    },
    common: {
      continue: "Continue",
      save: "Save",
      back: "Back",
      ok: "OK",
      retry: "Retry",
      processing: "Processing...",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      loading: "Loading...",
      success: "Success",
      error: "Error",
      warning: "Warning",
      info: "Info",
      loadingNotifications: "Loading notifications...",
      noMoreNotifications: "No more notifications",
      loadingMore: "Loading more notifications...",
    },
    yourRides: {
      title: "Your Rides",
      tabs: {
        Pending: "Pending",
        Cancelled: "Cancelled",
        Completed: "Completed",
        "In Progress": "On Going",
      },
      userSide: "User Side",
      driverSide: "Driver Side",
      chooseDashboard: "Please choose how you'd like to view your ride dashboard",
      verifyPassenger: "Please Verify Your Passenger",
      enterPin: "Enter PIN Number",
      verify: "Verify",
      noBookingsFound: "No Bookings Found",
      pullToRefresh: "Pull to refresh",
      rideCancelled: "Ride Cancelled",
      bookingCancelled: "Booking Cancelled",
      rideStarted: "Ride Started",
      bookingCompleted: "Booking Completed",
      bookingVerified: "Booking Verified",
      confirmStartRide: "Start Ride?",
      startRideMessage: "Are you sure you want to start this ride? This action will notify all passengers that the journey has begun.",
      cancel: "Cancel",
      startRide: "Start Ride",
      endRide: "End Ride",
      addPassengers: "Add Passengers",
    },
    inbox: {
      title: "Inbox",
      nameEn: "Mohammed Arshad",
      nameAr: "محمد أرشد",
      fromValue: "Al Khobar",
      toValue: "Ar Riyadh",
      dateValue: "Thu, 06 February",
      timeValue: "08 : 00 pm",
      from: "{{from}}",
      to: "{{to}}",
      date: "{{date}}",
      time: "{{time}}",
    },
    // verify-otp
    Verify: "Verify",
    "Please Verify Your Number": "Please Verify Your Number",
    "Please enter the six-digit verification code that we have sent to your mobile number ending in":
      "Please enter the six-digit verification code that we have sent to your mobile number ending in",
    "If you haven't received the code, please check your messages or":
      "If you haven't received the code, please check your messages or",
    "request a new code.": "request a new code.",
    endingDigits: " {{digits}}.",
    // passenger-select
    Passenger: "Passenger",
    "Select no. of passengers": "Select no. of passengers",
    "Passenger(s)": "Passenger(s)",
    // auto-complete
    "Search...": "Search...",
    // city-search
    "Enter the full address": "Enter the full address",
    "No items.": "No items.",
    "Mobile number*": "Mobile number*",
    // ride-status-item
    Completed: "Completed",
    Pending: "Pending",
    Cancelled: "Cancelled",
    Invoice: "Invoice",
    searchRide: {
      title: "Where you want to go ?",
      pickupPlaceholder: "Enter pickup location",
      dropPlaceholder: "Enter drop location",
      searchButton: "Search",
      "missingLocation": "Please select both pickup and drop-off locations.",
      "missingDate": "Please select a ride date."
    },
    locationSelect: {
      placeholder: "Search location...",
      emptyMessage: "No items found.",
    },
    datePicker: {
      scheduleTrip: "Schedule trip",
      pickDate: "Pick a date",
      today: "Today",
      tomorrow: "Tomorrow",
      apply: "Apply",
    },
    rideFilter: {
      filter: "Filter",
      resetAll: "Reset all",
      sortBy: "Sort by",
      clearAll: "Clear all",
      earliestDeparture: "Earliest departure",
      lowestPrice: "Lowest price",
      closeToDeparture: "Close to departure point",
      closeToArrival: "Close to arrival point",
      shortestRide: "Shortest ride",
      numberOfStops: "Number of stops",
      directRidesOnly: "Direct rides only",
      oneStop: "1 Stop",
      twoStopsOrMore: "2 Stops or more",
      trustAndSafety: "Trust and safety",
      verifiedProfile: "Verified Profile",
      amenities: "Amenities",
      carModel: "Car model",
      lastThreeYears: "Last 3 years",
      lastFiveYears: "Last 5 years",
      all: "All",
      apply: "Apply",
    },
    checkboxCard: {
      maxTwoInBack: "Max. 2 in the back",
      instantBooking: "Instant Booking",
      smokingAllowed: "Smoking allowed",
      petsAllowed: "Pets allowed",
      powerOutlets: "Power outlets",
      airConditioning: "Air conditioning",
      accessibleForDisabilities: "Accessible for passengers with disabilities",
    },
    rideDetails: {
      rideDetails: "Ride Details",
      pickup: "Pickup",
      drop: "Drop",
      pickupTime: "Pickup Time",
      dropTime: "Drop Time",
      alKhobar: "Al Khobar, Saudi Arabia",
      riyadh: "Riyadh, Saudi Arabia",
      departureTime: "13:00",
      arrivalTime: "17:40",
      carType: "Car Type",
      sedan: "Sedan",
      details: "Details",
      rarelyCancelsRides: "Rarely cancels rides",
      instantBooking: "Your booking will be confirmed instantly",
      fineWithSmoking: "I'm fine with smoking",
      passengers: "Passengers",
      priceSummary: "Price Summary",
      onePassenger: "1 Passenger",
      amountPaidToDriver: "Amount paid to the driver",
      serviceFeeAndVAT: "Service fee and VAT",
      totalPrice: "Total Price",
      manageRide: "Manage ride",
      ratings: "Ratings",
      abhimanyu: "Abhimanyu",
      karthik: "Karthik",
      chennai: "Chennai",
      banglaluru: "Banglaluru",
      rating: "4.5",
      currency: "SR",
    },
    payment: {
      selectPaymentMethod: "Select a payment method",
      creditDebitCards: "Credit & DEBIT CARDS",
      addNewCard: "+ ADD NEW CARD",
      otherUpiApps: "OTHER UPI APPS",
      addNew: "+ ADD NEW",
      amount: "Amount",
      pay: "PAY",
      waitingApproval: "Waiting for payment approval...",
      waitingSubtext: "Please wait while we verify your payment",
      bookingConfirmed: "Booking Confirmed",
      paymentSuccessMessage: "Your payment has been processed successfully and your booking is confirmed.",
      ok: "OK",
      visa: "Visa ending in 5775",
      mastercard: "Master ending in 5775",
      expiry: "Ex.date 06/27",
      applePay: "Apple Pay",
      samsungPay: "Samsung Pay",
      currency: "SR",
      timeout: "Payment Timeout",
      timeoutMessage: "Payment verification timed out. Please check your booking status or try again.",
      authFailed: "Authentication Failed",
      authFailedMessage: "Payment authentication failed or was cancelled.",
      authCancelled: "Authentication Cancelled",
      authCancelledMessage: "Payment authentication was cancelled.",
      processing: "Processing...",
      // Form labels and placeholders
      addNewCardTitle: "Add New Card",
      selectCardType: "Select Type of Card",
      cardHolderName: "Card Holder Name",
      cardHolderNamePlaceholder: "Enter cardholder name",
      cardNumber: "Card Number",
      cardNumberPlaceholder: "1234 5678 9012 3456",
      expiryDate: "Expiry Date",
      expiryDatePlaceholder: "MM/YY",
      cvv: "CVV",
      cvvPlaceholder: "123",
      billingDetails: "Billing Details",
      email: "Email",
      emailPlaceholder: "Enter email",
      billingStreet: "Billing Street",
      billingStreetPlaceholder: "Enter street",
      billingCity: "Billing City",
      billingCityPlaceholder: "Enter city",
      billingState: "Billing State",
      billingStatePlaceholder: "Enter state",
      billingPostCode: "Billing Post Code",
      billingPostCodePlaceholder: "Enter post code",
      save: "Save",
      secureAuthentication: "Secure Authentication",
      done: "Done",
      redirectingToAuth: "Redirecting to authentication...",
      // Validation messages
      validationError: "Validation Error",
      enterCardholderName: "Please enter cardholder name.",
      enterValidCardNumber: "Please enter a valid card number (16 digits).",
      enterValidExpiryDate: "Please enter a valid expiry date (MM/YY).",
      enterValidCVV: "Please enter a valid CVV.",
      enterValidEmail: "Please enter a valid email address.",
      // Payment errors
      paymentError: "Payment Error",
      paymentAuthorizationFailed: "Payment authorization failed",
      paymentProcessingFailed: "Payment processing failed",
      networkError: "Network Error",
      checkInternetConnection: "Please check your internet connection and try again.",
      timeoutError: "Timeout Error",
      requestTimedOut: "Request timed out. Please try again.",
      serverError: "Server Error",
      invalidServerResponse: "Invalid response from server. Please try again later.",
      failedToAuthorizePayment: "Failed to authorize payment. Please try again.",
      // Card management
      editCard: "Edit Card",
      deleteCard: "Delete Card",
      deleteCardTitle: "Delete Card",
      deleteCardMessage: "Are you sure you want to delete this card? This action cannot be undone.",
      delete: "Delete",
      editCardTitle: "Edit Card",
      updateCard: "Update Card",
      updating: "Updating...",
      cardUpdated: "Card Updated",
      cardUpdatedMessage: "Your card details have been updated successfully.",
      failedToUpdateCard: "Failed to update card details",
      error: "Error",
      // Additional missing keys
      creating: "Creating...",
      searchingRides: "Searching for rides...",
      noCardsFound: "No saved cards found",
      pullToRefresh: "Pull down to refresh or add a new card",
      loadingCards: "Loading cards...",
      refreshingCards: "Refreshing cards...",
      cardDeletedSuccessfully: "Card deleted successfully",
      failedToDeleteCard: "Failed to delete card",
      failedToLoadCards: "Failed to load cards",
      failedToRefreshCards: "Failed to refresh cards",
    },
    chat: {
      abhimanyu: "Abhimanyu",
      alKhobar: "Al Khobar, Saudi Arabia",
      awaitingApproval: "Awaiting for approval",
      new: "New",
      guidelinesNotice:
        "We may moderate messages. You can also report inappropriate ones from",
      guidelinesPage: "our guidelines page.",
      scamWarning:
        "To avoid scams, never visit links sent by members to pay or transfer money.",
      learnMore: "Learn more.",
      yourMessage: "Your message",
      messagingGuidelines: "Messaging guidelines",
      guidelines1:
        "Please don't include your phone number, email address or any website URLs.",
      guidelines2:
        "We may filter all or part of your message, in particular if it includes contact information, as this is contrary to our",
      terms: "Terms and Conditions.",
      close: "Close",
      hello: "Hello",
      dateTime: "Thu, 06 February 08 : 00 pm",
    },
    chatProfile: {
      profile: "Profile",
      reportNumber: "Report this number",
      abhimanyu: "Abhimanyu",
      alBalad: "Al Balad, Saudi Arabia",
      confirmedMail: "Confirmed mail id",
      confirmedPhone: "Confirmed phone number",
      ridePublished: "ride published",
      about: "About",
      phoneNumber: "Phone Number",
      mailId: "Mail id",
      experience: "Experience",
      intermediate: "Intermediate",
      aboutText:
        "Making travel more convenient and cost-effective for passengers. With a strong commitment to safety and punctuality, he ensures a smooth and comfortable ride. His reliable service helps commuters share journeys efficiently while fostering a sense of community on the road.",
    },
    passengerProfile: {
      profile: "Profile",
      reportNumber: "Report this number",
      abhimanyu: "Abhimanyu",
      alBalad: "Al Balad, Saudi Arabia",
      confirmedMail: "Confirmed mail id",
      confirmedPhone: "Confirmed phone number",
      about: "About",
      aboutText:
        "Making travel more convenient and cost-effective for passengers. With a strong commitment to safety and punctuality, he ensures a smooth and comfortable ride. His reliable service helps commuters share journeys efficiently while fostering a sense of community on the road.",
    },
    tabs: {
      home: "Home",
      publish: "Publish",
      yourRides: "Your Rides",
      inbox: "Inbox",
      profile: "Profile",
    },
    pickupSelected: {
      title: "Where would you like to pick up passengers?",
    },
    locationSearchSelected: {
      label: "Select a location",
      continue: "Continue",
      whyExactLocation: "Why an exact location?",
    },
    dropoff: {
      title: "Where are you going to?",
      selectedTitle: "Where would you like to drop off passengers?",
    },
    route: {
      title: "What's your route?",
      option1: {
        title: "04 hr 15 min",
        description: "346 km - Hosur Rd and NH 4/NH 44/NH 48",
      },
      option2: {
        title: "04 hr 40 min",
        description: "346 km - Hosur Rd and NH 4/NH 44/NH 48",
      },
      option3: {
        title: "05 hr 10 min",
        description: "346 km - Hosur Rd and NH 4/NH 44/NH 48",
      },
    },
    stopovers: {
      title: "Add stopovers to get more passengers",
      addCity: "Add city",
      city1: "Dammam",
      city2: "Sedra Resort",
      city3: "Judah",
    },
    stopoversPreview: {
      title: "These are the best places to stop. OK for you?",
      start: "Dammam",
      end: "Riyadh",
      stop1: {
        title: "Heritage Village",
        desc: "Corniche Rd, Dammam, Saudi Arabia",
      },
    },
    date: {
      title: "When Are you Going ?",
    },
    time: {
      title: "At what time will you pick passenger up?",
      am: "AM",
      pm: "PM",
    },
    passengerCount: {
      title: "So how many ViaCars passengers can you take?",
      options: "Passenger options",
      maxTwoInBack: "Max. 2 in the back",
      comfortHint: "Think comfort, keep the middle seat empty",
    },
    pricing: {
      title: "Set your price per seat",
      recommended: "Recommended Price:",
      hint: "Perfect price for this ride! You'll get passengers in no time.",
      showPrices: "Show Prices",
    },
    showPricing: {
      rideDetails: "Ride Details",
      pickup: "Pickup",
      drop: "Drop",
      stopover: "Stopover",
      alKhobar: "Al Khobar, Saudi Arabia",
      riyadh: "Riyadh, Saudi Arabia",
      heritageVillage: "Heritage Village, Dammam, Saudi Arabia",
      insufficientRouteData: "Insufficient route data. Please go back and complete your ride details.",
    },
    returnRide: {
      title: "Coming back as well?\nPublish your return ride now!",
      publishNow: "Publish my return ride",
      publishLater: "I'll publish my return ride later",
    },
    publishComment: {
      title: "Anything to add about your ride?",
      placeholder:
        "Flexible about where and when to meet? Not taking motorway? Got limited space in your boot? Keep passenger in the loop.",
      publish: "Publish ride",
    },
    publishRide: {
      success:
        "Your ride listing has been\nsuccessfully published and is active!",
      verifyProfile: "One last step: we need to verify your profile",
      verifyId: "Verify ID",
      confirmedPhone: "Confirmed phone number",
      seeMyRide: "See my ride",
      emailSent:
        "We've sent a verification link to your email address. Please check your inbox.",
      ok: "OK",
    },
    yourRide: {
      title: "Ride Plan",
      pickup: "Pickup",
      drop: "Drop",
      pickupTime: "Pickup Time",
      dropTime: "Drop Time",
      seePublication: "See your publication online",
      views: "3 Views",
      editPublication: "Edit your publication",
      alKhobar: "Al Khobar, Saudi Arabia",
      riyadh: "Riyadh, Saudi Arabia",
      departureTime: "13:00",
      arrivalTime: "17:40",
    },
    yourPublication: {
      title: "Your publication",
      itinerary: "Itinerary details",
      route: "Route",
      price: "Price",
      priceSub: "Passengers will pay in cash",
      seatOptions: "Seat and options",
      duplicate: "Duplicate your publication",
      publishReturn: "Publish your return ride",
      cancel: "Cancel your ride",
    },
    itinerary: {
      title: "Itinerary Details",
      start: "Dammam",
      stopTitle: "Heritage Village",
      stopDesc: "Corniche Rd, Dammam, Saudi Arabia",
      end: "Riyadh",
      date: "Date",
      dateValue: "Thu, 13 February",
      time: "Time",
      timeValue: "07:00 AM",
      manageStopovers: "Manage stopovers",
    },
    stopoversEdit: {
      title: "Add stopovers to get more passengers",
      addCity: "Add city",
      continue: "Continue",
      cities: ["Dammam", "Sedra Resort", "Judah"],
    },
    rideStatusItem: {
      departureTime: "13:00",
      departureLocation: "Al Khobar, Saudi Arabia",
      duration: "4h 40m",
      arrivalTime: "17:40",
      arrivalLocation: "Ar Riyadh, Saudi Arabia",
      price: "SR 560.00",
      driverName: "Abhimanyu",
      rating: "4.5",
      Completed: "Completed",
      Invoice: "Invoice",
      Pending: "Pending",
      Cancelled: "Cancelled",
    },
    notifications: {
      title: "Notifications",
      emptyTitle: "No notifications yet",
      emptySubtitle: "You'll see your notifications here",
      bookingConfirmed: "Your booking confirmed",
      bookingCompleted: "Your booking completed",
      bookingCancelled: "Your booking cancelled",
      defaultMessage: "Lorem ipsum dolor sit amet, consectetur",
    },
  },
  booking: {
    ride: {
      title: "Available Rides",
      location: "Chennai, Tamil Nadu Jasma...",
      todayPassenger: "Today, 1 passenger",
      filters: "Filters",
      today: "Today",
      passengers: "Passengers",
      noRides: "No rides available for your search criteria.",
      createAlert: "Create a Ride Alert",
      enterEmail: "Enter your email ID, and we'll notify you.",
      pickup: "Pickup",
      pickupLocation: "Al Khobar, Saudi Arabia",
      drop: "Drop",
      dropLocation: "Riyadh, Saudi Arabia",
      emailInstruction:
        "Please enter your full email address so we can send you ride details and notifications.",
      emailPlaceholder: "Enter your email address",
      rideAlert: "Ride Alert",
      chennai: "Chennai, Tamil Nadu Jasma...",
      alKhobar: "Al Khobar, Saudi Arabia",
      riyadh: "Riyadh, Saudi Arabia",
      abhimanyu: "Abhimanyu",
      searching: "Searching for rides...",
      creating: "Creating alert...",
    },
    rideItem: {
      departureTime: "13:00",
      passengers: "passengers",
      departureLocation: "Al Khobar, Saudi Arabia",
      duration: "4h 40m",
      arrivalTime: "17:40",
      arrivalLocation: "Ar Riyadh, Saudi Arabia",
      price: "SR 560.00",
      driverName: "Abhimanyu",
      rating: "4.5",
      pickup: "PICKUP",
      drop: "DROP",
    },
  },
};

const error = {
  rideCreationFailed: "Ride Creation Failed",
  serverError: "Server Error",
  serverErrorMessage: "Something went wrong on our end. Please try again later.",
  unknownError: "Error",
  unexpectedError: "Unexpected Error",
  networkError: "Network error. Please check your connection and try again.",
};

const enWithError = { ...en, error };

export default enWithError;
