require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods', deterministic_uuids: false
prepare_react_native_project!

target 'ViaCar' do
  use_expo_modules!

  config_command = ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1' \
    ? ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"] \
    : ['npx', 'expo-modules-autolinking', 'react-native-config', '--json', '--platform', 'ios']

  pod 'react-native-google-maps',
    path: File.dirname(`node --print "require.resolve('react-native-maps/package.json')"`)

  config = use_native_modules!(config_command)

  # Use dynamic frameworks to support Firebase Swift pods
  use_frameworks! linkage: :static

  use_react_native!(
    path: config[:reactNativePath],
    hermes_enabled: podfile_properties['expo.jsEngine'].nil? || podfile_properties['expo.jsEngine'] == 'hermes',
    app_path: "#{Pod::Config.instance.installation_root}/..",
    privacy_file_aggregation_enabled: podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false'
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      mac_catalyst_enabled: false,
      ccache_enabled: podfile_properties['apple.ccacheEnabled'] == 'true'
    )

    # Xcode 14 resource-bundle code-signing fix
    installer.target_installation_results.pod_target_installation_results
      .each do |_pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end